// Staff API Service
import { request } from './apiClient';
import { getAuthToken } from './authService';
import type { StaffModel, StaffDetailsModel } from '../Interfaces';

const API_BASE_URL = (import.meta as any)?.env?.VITE_API_BASE_URL || 'https://cliniassistsapi-cmb3dcceapfwa6ah.centralus-01.azurewebsites.net/api';

export interface CreateStaffDto {
  clinicId: number;
  fullName: string;
  role: string;
  phone: string;
  email: string;
}

export interface CreateStaffDetailDto {
  staffId?: string;
  enterpriseId?: number;
  clinicId?: number;
  firstName: string;
  lastName: string;
  dateOfBirth?: string;
  gender?: string;
  email: string;
  phone: string;
  address?: string;
  licenseNumber?: string;
  licenseExpiry?: string; // ✅ DateTime on backend
  specialtyId?: number; // ✅ int? on backend
  yearsExperience?: number; // ✅ int? on backend
  education?: string;
  certifications?: string;
  languages?: string;
  joiningDate?: string;
  employmentStatus?: string;
  availability?: string;
  insuranceDetails?: string;
  emergencyContact?: string;
  bio?: string;
  profilePhotoUrl?: string;
  achievements?: string;
  publications?: string;
  socialLinks?: string;
  rolesAssigned?: string; // ✅ string? on backend (not int)
}

export interface UpdateStaffDto extends Partial<CreateStaffDto> {}

export function listStaff(clinicId?: number): Promise<StaffModel[]> {
  const suffix = clinicId ? `?clinicId=${clinicId}` : "";
  return request<StaffModel[]>(`/staff${suffix}`);
}

export function getStaff(staffId: number): Promise<StaffModel> {
  return request<StaffModel>(`/staff/${staffId}`);
}

export function createStaff(payload: CreateStaffDto): Promise<StaffModel> {
  return request<StaffModel>("/staff", {
    method: "POST",
    body: JSON.stringify(payload)
  });
}

export function updateStaff(staffId: number, payload: UpdateStaffDto): Promise<StaffModel> {
  return request<StaffModel>(`/staff/${staffId}`, {
    method: "PUT",
    body: JSON.stringify(payload)
  });
}

export function deleteStaff(staffId: number): Promise<void> {
  return request<void>(`/staff/${staffId}`, { method: "DELETE" });
}

// Staff Details
export function listStaffDetails(): Promise<StaffDetailsModel[]> {
  return request<StaffDetailsModel[]>("/staffdetails");
}

export function getStaffDetail(staffId: number): Promise<StaffDetailsModel> {
  return request<StaffDetailsModel>(`/staffdetails/${staffId}`);
}

export function createStaffDetail(payload: CreateStaffDetailDto): Promise<StaffDetailsModel> {
  // Remove staffId before sending - it's auto-generated by backend
  const cleanPayload = { ...payload };
  delete cleanPayload.staffId;

  // 🔍 DEBUG LOGGING - Check payload before sending to backend
  console.log("=== SENDING TO StaffDetail/CreateRoleBasedProfile ===");
  console.log("Full Payload:", cleanPayload);
  console.log("enterpriseId:", cleanPayload.enterpriseId, "(Type:", typeof cleanPayload.enterpriseId, ")");
  console.log("clinicId:", cleanPayload.clinicId, "(Type:", typeof cleanPayload.clinicId, ")");
  console.log("licenseExpiry:", cleanPayload.licenseExpiry, "(Type:", typeof cleanPayload.licenseExpiry, ")");
  console.log("yearsExperience:", cleanPayload.yearsExperience, "(Type:", typeof cleanPayload.yearsExperience, ")");
  console.log("specialtyId:", cleanPayload.specialtyId, "(Type:", typeof cleanPayload.specialtyId, ")");
  console.log("rolesAssigned:", cleanPayload.rolesAssigned, "(Type:", typeof cleanPayload.rolesAssigned, ")");
  
  // Use the request function which automatically includes required headers (X-Enterprise-Id, X-Clinic-Id, Authorization)
  return request<StaffDetailsModel>("/StaffDetail/CreateRoleBasedProfile", {
    method: "POST",
    body: JSON.stringify(cleanPayload)
  })
    .then(response => {
      console.log("✅ Staff profile created successfully");
      return response;
    })
    .catch(err => {
      console.error("❌ Error calling CreateRoleBasedProfile:", err);
      throw err;
    });
}

export function updateStaffDetail(staffId: number, payload: Partial<CreateStaffDetailDto>): Promise<StaffDetailsModel> {
  // 🔍 DEBUG LOGGING - Check payload before sending to backend
  console.log("=== UPDATING STAFF - SENDING TO BACKEND ===");
  console.log("Staff ID:", staffId);
  console.log("Update Payload:", payload);
  console.log("licenseExpiry:", payload.licenseExpiry, "(Type:", typeof payload.licenseExpiry, ")");
  console.log("yearsExperience:", payload.yearsExperience, "(Type:", typeof payload.yearsExperience, ")");
  console.log("specialtyId:", payload.specialtyId, "(Type:", typeof payload.specialtyId, ")");
  
  return request<StaffDetailsModel>(`/staffdetails/${staffId}`, {
    method: "PUT",
    body: JSON.stringify(payload)
  });
}

// Get staff profile by clinic ID (new endpoint from user requirement)
// Backend endpoint: GetStaffProfileByClinicId with int ClinicId parameter
export function getStaffProfileByClinicId(clinicId: number): Promise<StaffDetailsModel[]> {
  console.log('📞 API CALL: getStaffProfileByClinicId with ClinicId:', clinicId);
  const endpoint = `/StaffDetail/GetStaffProfileByClinicId?ClinicId=${clinicId}`;
  return request<StaffDetailsModel[]>(endpoint);
}

